// src/lib/components/ShelfHero.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import MetaballCanvas from '$lib/components/canvas/MetaballCanvas.svelte';
	import { extractDominantColor } from '$lib/dominant-color';
	import { proxyImg } from '$lib/img';
	import type { Book } from '$lib/goodreads';

	// --black #1a1a14 as normalized RGB
	const BG_COLOR: [number, number, number] = [26 / 255, 26 / 255, 20 / 255];

	interface Props {
		featured: Book | null;
		featuredLabel: string;
	}

	let { featured, featuredLabel }: Props = $props();

	let coverEl: HTMLImageElement | undefined = $state();
	let descEl: HTMLParagraphElement | undefined = $state();
	let target = $state<{ x: number; y: number } | null>(null);
	let color = $state<[number, number, number]>(BG_COLOR);
	let expanded = $state(false);
	let contentHeight = $state(0);
	let metaballsHidden = $state(true);

	function toggleExpanded() {
		if (descEl) contentHeight = descEl.scrollHeight;
		metaballsHidden = true;
		setTimeout(() => { metaballsHidden = false; }, 1000);
		expanded = !expanded;
	}

	onMount(() => {
		if (!featured?.coverUrl) {
			metaballsHidden = false;
			return;
		}
		let cancelled = false;
		extractDominantColor(proxyImg(featured.coverUrl, 200)).then((c) => {
			if (cancelled) return;
			if (c) color = c;
			metaballsHidden = false;
		});
		return () => { cancelled = true; };
	});

	function updateTarget() {
		const rect = coverEl?.getBoundingClientRect();
		if (!rect) return;
		target = { x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 };
	}

	function clearTarget() {
		target = null;
	}

	const patternUrl = $derived.by(() => {
		const cssColor = `rgb(${Math.round(color[0] * 255)}, ${Math.round(color[1] * 255)}, ${Math.round(color[2] * 255)})`;
		const tileW = 900;
		const tileH = 460;
		const phrase = "WHAT'S ON MY SHELF? ".repeat(10);
		const rows = [
			{ y: 38, size: 26, offset: 0 },
			{ y: 92, size: 16, offset: -140 },
			{ y: 148, size: 34, offset: 70 },
			{ y: 200, size: 20, offset: -60 },
			{ y: 258, size: 44, offset: 110 },
			{ y: 316, size: 18, offset: -90 },
			{ y: 366, size: 28, offset: 30 },
			{ y: 420, size: 14, offset: -50 },
		];
		const rowsSvg = rows
			.map(
				(r) =>
					`<text x='${r.offset}' y='${r.y}' font-family='monospace' font-size='${r.size}' font-weight='700' letter-spacing='${Math.round(r.size * 0.3)}' fill='${cssColor}'>${phrase}</text>`,
			)
			.join('');
		const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='${tileW}' height='${tileH}' viewBox='0 0 ${tileW} ${tileH}'>${rowsSvg}</svg>`;
		return `url("data:image/svg+xml;utf8,${encodeURIComponent(svg)}")`;
	});

	const shadowRgb = $derived(
		`${Math.round(color[0] * 255)} ${Math.round(color[1] * 255)} ${Math.round(color[2] * 255)}`,
	);
</script>

<section
	class="relative flex min-h-dvh items-start justify-center overflow-hidden bg-black px-6 pt-24 pb-18 md:items-center md:px-9 md:py-18"
>
	<div
		class="pointer-events-none absolute inset-0"
		style="z-index: 0; background-image: {patternUrl}; background-repeat: repeat; opacity: 0.13;"
		aria-hidden="true"
	></div>

	<div
		class="pointer-events-none absolute inset-0 transition-opacity duration-1000 ease-out"
		style="z-index: 2; opacity: {metaballsHidden ? 0 : 1};"
	>
		<MetaballCanvas {color} trackCursor={false} {target} />
	</div>

	<h1 class="sr-only">what's on my shelf?</h1>

	{#if featured}
		<div class="relative z-10 mx-auto grid w-full max-w-6xl grid-cols-1 items-center gap-6 md:grid-cols-2 md:gap-12">
			<a
				href={`https://www.goodreads.com/book/show/${featured.id}`}
				target="_blank"
				rel="noopener noreferrer"
				class="group/cover flex items-center justify-center md:justify-end"
				onmouseenter={updateTarget}
				onmouseleave={clearTarget}
			>
				{#if featured.coverUrl}
					<img
						bind:this={coverEl}
						src={proxyImg(featured.coverUrl, 400)}
						alt={featured.cleanTitle}
						width={featured.coverW ?? 400}
						height={featured.coverH ?? 600}
						fetchpriority="high"
						loading="eager"
						style="--shadow-rgb: {shadowRgb};"
						class="block w-full max-w-[18rem] shadow-[0_20px_50px_-15px_rgb(var(--shadow-rgb)/0.45)] transition duration-700 group-hover/cover:-translate-y-1 group-hover/cover:-rotate-[1.3deg] group-hover/cover:shadow-[0_50px_120px_-20px_rgb(var(--shadow-rgb)/0.8)] md:max-h-[60dvh] md:w-[clamp(18rem,32vw,26rem)] md:max-w-none"
					/>
				{/if}
			</a>

			<div class="flex flex-col gap-3 text-white md:max-w-md">
				<a
					href={`https://www.goodreads.com/book/show/${featured.id}`}
					target="_blank"
					rel="noopener noreferrer"
					class="flex flex-col gap-3"
				>
					<div class="font-mono text-xs uppercase tracking-pill text-coin">
						{featuredLabel}
					</div>
					<h2 class="text-3xl font-bold leading-tight md:text-4xl">{featured.cleanTitle}</h2>
					<div class="text-base opacity-70">
						{featured.author}{#if featured.series}
							{' · '}
							{featured.series} #{featured.seriesNumber}
						{/if}
					</div>
				</a>

				{#if featured.description}
					<div>
						<p
							bind:this={descEl}
							style={expanded && contentHeight > 0 ? `max-height: ${contentHeight}px;` : undefined}
							class={[
								'overflow-hidden whitespace-pre-line text-sm leading-relaxed opacity-75 transition-[max-height] duration-500 ease-out md:!max-h-none md:text-base',
								expanded ? '' : 'max-md:max-h-18',
							].join(' ')}
						>
							{featured.description}
						</p>
						<button
							type="button"
							onclick={toggleExpanded}
							class="mt-1.5 font-mono text-xs uppercase tracking-hero text-coin underline underline-offset-4 transition-opacity hover:opacity-80 md:hidden"
						>
							{expanded ? 'show less' : 'read more'}
						</button>
					</div>
				{/if}
			</div>
		</div>
	{/if}
</section>

// components/shelf/shelf-hero.tsx
"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { MetaballCanvas } from "@/components/canvas/metaball-canvas";
import { extractDominantColor } from "@/lib/dominant-color";
import type { Book } from "@/lib/goodreads";

// --black #1a1a14 as normalized RGB — metaballs start invisible on the black section.
const BG_COLOR: [number, number, number] = [26 / 255, 26 / 255, 20 / 255];

interface ShelfHeroProps {
  featured: Book | null;
  featuredLabel: string;
}

export function ShelfHero({ featured, featuredLabel }: ShelfHeroProps) {
  const coverRef = useRef<HTMLImageElement>(null);
  const descRef = useRef<HTMLParagraphElement>(null);
  const [target, setTarget] = useState<{ x: number; y: number } | null>(null);
  const [color, setColor] = useState<[number, number, number]>(BG_COLOR);
  const [expanded, setExpanded] = useState(false);
  const [contentHeight, setContentHeight] = useState(0);
  const [metaballsHidden, setMetaballsHidden] = useState(true);

  const toggleExpanded = useCallback(() => {
    if (descRef.current) setContentHeight(descRef.current.scrollHeight);
    setMetaballsHidden(true);
    setTimeout(() => setMetaballsHidden(false), 1000);
    setExpanded((x) => !x);
  }, []);

  useEffect(() => {
    if (!featured?.coverUrl) {
      setMetaballsHidden(false);
      return;
    }
    let cancelled = false;
    extractDominantColor(featured.coverUrl).then((c) => {
      if (cancelled) return;
      if (c) setColor(c);
      setMetaballsHidden(false);
    });
    return () => {
      cancelled = true;
    };
  }, [featured?.coverUrl]);

  const updateTarget = useCallback(() => {
    const rect = coverRef.current?.getBoundingClientRect();
    if (!rect) return;
    setTarget({ x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 });
  }, []);

  const clearTarget = useCallback(() => setTarget(null), []);

  const patternUrl = useMemo(() => {
    const cssColor = `rgb(${Math.round(color[0] * 255)}, ${Math.round(color[1] * 255)}, ${Math.round(color[2] * 255)})`;
    const tileW = 900;
    const tileH = 460;
    const phrase = "WHAT'S ON MY SHELF? ".repeat(10);
    const rows = [
      { y: 38, size: 26, offset: 0 },
      { y: 92, size: 16, offset: -140 },
      { y: 148, size: 34, offset: 70 },
      { y: 200, size: 20, offset: -60 },
      { y: 258, size: 44, offset: 110 },
      { y: 316, size: 18, offset: -90 },
      { y: 366, size: 28, offset: 30 },
      { y: 420, size: 14, offset: -50 },
    ];
    const rowsSvg = rows
      .map(
        (r) =>
          `<text x='${r.offset}' y='${r.y}' font-family='monospace' font-size='${r.size}' font-weight='700' letter-spacing='${Math.round(r.size * 0.3)}' fill='${cssColor}'>${phrase}</text>`
      )
      .join("");
    const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='${tileW}' height='${tileH}' viewBox='0 0 ${tileW} ${tileH}'>${rowsSvg}</svg>`;
    return `url("data:image/svg+xml;utf8,${encodeURIComponent(svg)}")`;
  }, [color]);

  return (
    <section
      className="relative flex min-h-[100dvh] items-start justify-center overflow-hidden px-6 pt-24 pb-16 md:items-center md:px-10 md:py-16"
      style={{ background: "var(--black)" }}
    >
      <div
        className="pointer-events-none absolute inset-0"
        style={{ zIndex: 0, backgroundImage: patternUrl, backgroundRepeat: "repeat", opacity: 0.13 }}
        aria-hidden="true"
      />

      <div
        className="pointer-events-none absolute inset-0 transition-opacity duration-1000 ease-out"
        style={{ zIndex: 2, opacity: metaballsHidden ? 0 : 1 }}
      >
        <MetaballCanvas color={color} trackCursor={false} target={target} />
      </div>

      <h1 className="sr-only">what&apos;s on my shelf?</h1>

      {featured ? (
        <div className="relative z-10 mx-auto grid w-full max-w-6xl grid-cols-1 items-center gap-6 md:grid-cols-2 md:gap-12">
          <a
            href={`https://www.goodreads.com/book/show/${featured.id}`}
            target="_blank"
            rel="noopener noreferrer"
            className="group/cover flex items-center justify-center md:justify-end"
            onMouseEnter={updateTarget}
            onMouseLeave={clearTarget}
          >
            {featured.coverUrl ? (
              <img
                ref={coverRef}
                src={featured.coverUrl}
                alt={featured.cleanTitle}
                style={{ "--shadow-rgb": `${Math.round(color[0] * 255)} ${Math.round(color[1] * 255)} ${Math.round(color[2] * 255)}` } as React.CSSProperties}
                className="block h-auto w-full shadow-[0_20px_50px_-15px_rgb(var(--shadow-rgb)/0.45)] transition duration-700 group-hover/cover:-translate-y-1 group-hover/cover:-rotate-[1.3deg] group-hover/cover:shadow-[0_50px_120px_-20px_rgb(var(--shadow-rgb)/0.8)] md:h-auto md:max-h-[60dvh] md:w-auto"
              />
            ) : null}
          </a>

          <div className="flex flex-col gap-4 md:max-w-md" style={{ color: "var(--white)" }}>
            <a
              href={`https://www.goodreads.com/book/show/${featured.id}`}
              target="_blank"
              rel="noopener noreferrer"
              className="flex flex-col gap-3"
            >
              <div className="font-mono text-xs uppercase tracking-[0.3em]" style={{ color: "var(--coin)" }}>
                {featuredLabel}
              </div>
              <h2 className="text-3xl font-bold leading-tight md:text-4xl">{featured.cleanTitle}</h2>
              <div className="text-base opacity-70">
                {featured.author}
                {featured.series ? (
                  <span>
                    {" · "}
                    {featured.series} #{featured.seriesNumber}
                  </span>
                ) : null}
              </div>
            </a>

            {featured.description ? (
              <div>
                <p
                  ref={descRef}
                  style={{
                    maxHeight: expanded && contentHeight > 0 ? `${contentHeight}px` : undefined,
                  }}
                  className={`overflow-hidden whitespace-pre-line text-sm leading-relaxed opacity-75 transition-[max-height] duration-500 ease-out md:!max-h-none md:text-base ${expanded ? "" : "max-md:max-h-[4.5rem]"}`}
                >
                  {featured.description}
                </p>
                <button
                  type="button"
                  onClick={toggleExpanded}
                  className="mt-2 font-mono text-xs uppercase tracking-[0.2em] underline underline-offset-4 transition-opacity hover:opacity-80 md:hidden"
                  style={{ color: "var(--coin)" }}
                >
                  {expanded ? "show less" : "read more"}
                </button>
              </div>
            ) : null}
          </div>
        </div>
      ) : null}
    </section>
  );
}
