// src/lib/components/messages/WordCloud.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { SvelteMap } from 'svelte/reactivity';
	import cloud from 'd3-cloud';
	import wordsData from '../../../../data/messages/dianchik/words-data.json';

	interface WordEntry {
		word: string;
		count: number;
	}

	type Who = 'both' | 'sam' | 'dianchik';

	const sam = wordsData.sam_cloud as WordEntry[];
	const dia = wordsData.dia_cloud as WordEntry[];

	const merged = new Map<string, number>();
	for (const e of sam) merged.set(e.word, (merged.get(e.word) ?? 0) + e.count);
	for (const e of dia) merged.set(e.word, (merged.get(e.word) ?? 0) + e.count);
	const both = [...merged.entries()]
		.sort((a, b) => b[1] - a[1])
		.slice(0, 300)
		.map(([word, count]) => ({ word, count }));

	interface LayoutWord {
		text: string;
		size: number;
		x: number;
		y: number;
		rotate: number;
		count: number;
	}

	function mulberry32(seed: number) {
		return () => {
			seed |= 0;
			seed = (seed + 0x6d2b79f5) | 0;
			let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
			t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
			return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
		};
	}

	let who = $state<Who>('both');
	let canvasEl: HTMLCanvasElement | undefined = $state();
	let containerEl: HTMLDivElement | undefined = $state();

	const layoutCache = new SvelteMap<string, LayoutWord[]>();

	function paint(layoutWords: LayoutWord[], baseColor: number[], max: number) {
		const canvas = canvasEl;
		if (!canvas) return;
		const ctx = canvas.getContext('2d')!;
		ctx.clearRect(0, 0, canvas.width, canvas.height);

		for (const w of layoutWords) {
			const opacity = 0.2 + ((w.count ?? 0) / max) * 0.8;
			ctx.save();
			ctx.translate(canvas.width / 2 + w.x, canvas.height / 2 + w.y);
			ctx.rotate((w.rotate * Math.PI) / 180);
			ctx.font = `${w.size}px Jost, sans-serif`;
			ctx.fillStyle = `rgba(${baseColor[0]},${baseColor[1]},${baseColor[2]},${opacity})`;
			ctx.textAlign = 'center';
			ctx.textBaseline = 'middle';
			ctx.fillText(w.text ?? '', 0, 0);
			ctx.restore();
		}
	}

	function draw() {
		const canvas = canvasEl;
		const container = containerEl;
		if (!canvas || !container) return;

		const width = container.clientWidth;
		const height = 400;
		canvas.width = width * 2;
		canvas.height = height * 2;
		canvas.style.width = `${width}px`;
		canvas.style.height = `${height}px`;

		const words = who === 'sam' ? sam : who === 'dianchik' ? dia : both;
		const max = words[0]?.count ?? 1;

		const baseColor =
			who === 'sam' ? [30, 30, 30] : who === 'dianchik' ? [180, 140, 20] : [60, 60, 60];

		const cacheKey = `${who}:${width}`;
		const cached = layoutCache.get(cacheKey);
		if (cached) {
			paint(cached, baseColor, max);
			return;
		}

		const rng = mulberry32(42);
		const layout = cloud()
			.size([width * 2, height * 2])
			.words(
				words.map((w) => ({
					text: w.word,
					size: 14 + Math.pow(w.count / max, 0.6) * 120,
					count: w.count,
				}))
			)
			.padding(1)
			.rotate(() => (rng() > 0.7 ? 90 : 0))
			.random(rng)
			.font('Jost, sans-serif')
			.fontSize((d) => (d as { size: number }).size)
			.on('end', (layoutWords: LayoutWord[]) => {
				layoutCache.set(cacheKey, layoutWords);
				paint(layoutWords, baseColor, max);
			});

		layout.start();
	}

	onMount(() => {
		draw();

		let timeout: ReturnType<typeof setTimeout>;
		const onWhoChange = () => {
			layoutCache.clear();
			draw();
		};
		const onResize = () => {
			clearTimeout(timeout);
			layoutCache.clear();
			timeout = setTimeout(draw, 150);
		};
		window.addEventListener('resize', onResize);

		// Watch `who` via an effect scoped inside onMount so it re-runs cleanly
		const stopEffect = $effect.root(() => {
			$effect(() => {
				// eslint-disable-next-line @typescript-eslint/no-unused-expressions
				who;
				onWhoChange();
			});
		});

		return () => {
			clearTimeout(timeout);
			window.removeEventListener('resize', onResize);
			stopEffect();
		};
	});
</script>

<div>
	<div class="mb-3 flex items-baseline justify-between">
		<span class="font-mono text-xs tracking-[0.16em] text-zinc-600">word cloud</span>
		<div class="flex gap-3">
			{#each ['both', 'dianchik', 'sam'] as w (w)}
				<button
					onclick={() => (who = w as Who)}
					class="font-mono text-[10px] tracking-wider transition-colors {who === w
						? 'text-black'
						: 'text-zinc-600 hover:text-black'}"
				>
					{w}
				</button>
			{/each}
		</div>
	</div>
	<div bind:this={containerEl} class="w-full">
		<canvas bind:this={canvasEl}></canvas>
	</div>
</div>

// components/messages/word-cloud.tsx
"use client";

import { useEffect, useRef, useState, useCallback } from "react";
import cloud from "d3-cloud";
import wordsData from "@/data/messages/dianchik/words-data.json";

interface WordEntry {
  word: string;
  count: number;
}

type Who = "both" | "sam" | "dianchik";

const sam = wordsData.sam_cloud as WordEntry[];
const dia = wordsData.dia_cloud as WordEntry[];

const merged = new Map<string, number>();
for (const e of sam) merged.set(e.word, (merged.get(e.word) ?? 0) + e.count);
for (const e of dia) merged.set(e.word, (merged.get(e.word) ?? 0) + e.count);
const both = [...merged.entries()]
  .sort((a, b) => b[1] - a[1])
  .slice(0, 300)
  .map(([word, count]) => ({ word, count }));

interface LayoutWord {
  text: string;
  size: number;
  x: number;
  y: number;
  rotate: number;
  count: number;
}

// Seeded PRNG so layout is deterministic
function mulberry32(seed: number) {
  return () => {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function WordCloud() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const [who, setWho] = useState<Who>("both");
  const layoutCache = useRef<Map<string, LayoutWord[]>>(new Map());

  const paint = useCallback((layoutWords: LayoutWord[], baseColor: number[], max: number) => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d")!;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    for (const w of layoutWords) {
      const opacity = 0.2 + ((w.count ?? 0) / max) * 0.8;
      ctx.save();
      ctx.translate(canvas.width / 2 + w.x, canvas.height / 2 + w.y);
      ctx.rotate((w.rotate * Math.PI) / 180);
      ctx.font = `${w.size}px Jost, sans-serif`;
      ctx.fillStyle = `rgba(${baseColor[0]},${baseColor[1]},${baseColor[2]},${opacity})`;
      ctx.textAlign = "center";
      ctx.textBaseline = "middle";
      ctx.fillText(w.text ?? "", 0, 0);
      ctx.restore();
    }
  }, []);

  const draw = useCallback(() => {
    const canvas = canvasRef.current;
    const container = containerRef.current;
    if (!canvas || !container) return;

    const width = container.clientWidth;
    const height = 400;
    canvas.width = width * 2;
    canvas.height = height * 2;
    canvas.style.width = `${width}px`;
    canvas.style.height = `${height}px`;

    const words = who === "sam" ? sam : who === "dianchik" ? dia : both;
    const max = words[0]?.count ?? 1;

    const baseColor = who === "sam"
      ? [30, 30, 30]
      : who === "dianchik"
        ? [180, 140, 20]
        : [60, 60, 60];

    const cacheKey = `${who}:${width}`;
    const cached = layoutCache.current.get(cacheKey);
    if (cached) {
      paint(cached, baseColor, max);
      return;
    }

    const rng = mulberry32(42);
    const layout = cloud()
      .size([width * 2, height * 2])
      .words(
        words.map((w) => ({
          text: w.word,
          size: 14 + Math.pow(w.count / max, 0.6) * 120,
          count: w.count,
        }))
      )
      .padding(1)
      .rotate(() => (rng() > 0.7 ? 90 : 0))
      .random(rng)
      .font("Jost, sans-serif")
      .fontSize((d) => (d as { size: number }).size)
      .on("end", (layoutWords: LayoutWord[]) => {
        layoutCache.current.set(cacheKey, layoutWords);
        paint(layoutWords, baseColor, max);
      });

    layout.start();
  }, [who, paint]);

  useEffect(() => {
    draw();
    let timeout: ReturnType<typeof setTimeout>;
    const onResize = () => {
      clearTimeout(timeout);
      layoutCache.current.clear();
      timeout = setTimeout(draw, 150);
    };
    window.addEventListener("resize", onResize);
    return () => {
      clearTimeout(timeout);
      window.removeEventListener("resize", onResize);
    };
  }, [draw]);

  return (
    <div>
      <div className="mb-3 flex items-baseline justify-between">
        <span className="font-mono text-xs tracking-[0.16em] text-zinc-400">
          word cloud
        </span>
        <div className="flex gap-3">
          {(["both", "dianchik", "sam"] as Who[]).map((w) => (
            <button
              key={w}
              onClick={() => setWho(w)}
              className={`font-mono text-[10px] tracking-wider transition-colors ${
                who === w ? "text-black" : "text-zinc-400 hover:text-zinc-600"
              }`}
            >
              {w}
            </button>
          ))}
        </div>
      </div>
      <div ref={containerRef} className="w-full">
        <canvas ref={canvasRef} />
      </div>
    </div>
  );
}
