// app/art/[slug]/page.tsx
import { notFound } from "next/navigation";
import Link from "next/link";
import type { Metadata } from "next";
import { sketches, getSketch } from "@/lib/art/registry";
import { ArtRedirect } from "./redirect";

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
  return sketches.map((s) => ({ slug: s.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const sketch = getSketch(slug);
  if (!sketch) return { title: "not found" };
  const ogUrl = `/art/og/${sketch.slug}.png`;
  return {
    title: `${sketch.title} — art — threesam`,
    description: `${sketch.title} (${sketch.date}), generative sketch.`,
    openGraph: {
      title: `${sketch.title} — threesam`,
      description: `${sketch.title} (${sketch.date}).`,
      images: [ogUrl],
    },
    twitter: {
      card: "summary_large_image",
      images: [ogUrl],
    },
  };
}

/**
 * Thin shell page: server-renders per-sketch metadata (title, og:image, etc.)
 * so crawlers see a rich social card, and client-redirects humans to the
 * scroll-snap gallery at /art#<slug>.
 */
export default async function ArtSketchPage({ params }: Props) {
  const { slug } = await params;
  const sketch = getSketch(slug);
  if (!sketch) notFound();

  const target = `/art#${sketch.slug}`;
  return (
    <main
      className="flex h-[100dvh] items-center justify-center"
      style={{ backgroundColor: "var(--black)", color: "var(--white)" }}
    >
      <ArtRedirect target={target} />
      <noscript>
        <Link href={target} className="underline">
          continue to {sketch.title}
        </Link>
      </noscript>
    </main>
  );
}

// src/routes/anything-but-analog/[slug]/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import SeoHead from '$lib/components/SeoHead.svelte';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();
  const { sketch } = $derived(data);

  const target = $derived(`/anything-but-analog#${sketch.slug}`);
  const ogUrl = $derived(`/og/anything-but-analog/${sketch.slug}.png`);

  onMount(() => {
    window.location.replace(target);
  });
</script>

<SeoHead
  title="{sketch.title} — anything but analog"
  description="{sketch.title} ({sketch.date}), generative sketch."
  ogImage={ogUrl}
  canonical="/anything-but-analog/{sketch.slug}"
/>

<!--
  Server renders rich social metadata so crawlers see the sketch title/OG.
  The onMount above redirects humans to the scroll-snap gallery at
  /anything-but-analog#<slug> — mirrors ArtRedirect in the Next.js original.
-->
<main
  class="flex h-dvh items-center justify-center"
  style="background-color: var(--black); color: var(--white);"
>
  <noscript>
    <a href={target} class="underline">continue to {sketch.title}</a>
  </noscript>
</main>
