// components/messages/dana-label.tsx
"use client";

import { useEffect, useState } from "react";

const CHARS = ["I", "_", "E", "-"];

export function DanaLabel() {
  const [idx, setIdx] = useState(0);

  useEffect(() => {
    const id = setInterval(() => setIdx((i) => (i + 1) % CHARS.length), 2000);
    return () => clearInterval(id);
  }, []);

  return (
    <>D<span className="inline-block w-6 text-center">{CHARS[idx]}</span>ANA</>
  );
}

// src/lib/components/messages/DanaLabel.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	const CHARS = ['I', '_', 'E', '-'];

	let idx = $state(0);

	onMount(() => {
		const id = setInterval(() => {
			idx = (idx + 1) % CHARS.length;
		}, 2000);
		return () => { clearInterval(id); };
	});
</script>

D<span class="inline-block w-[0.9em] text-center">{CHARS[idx]}</span>ANA
