// components/messages/pet-names.tsx
import petData from "@/data/messages/dianchik/petnames-data.json";

interface PetName {
  name: string;
  count: number;
}

const sam = petData.sam as PetName[];
const dia = petData.dianchik as PetName[];
const samMax = sam[0]?.count ?? 1;
const diaMax = dia[0]?.count ?? 1;

function NameBar({ name, count, max, color }: { name: string; count: number; max: number; color: string }) {
  const pct = (count / max) * 100;
  return (
    <div className="flex items-center gap-2">
      <span className="w-24 shrink-0 truncate text-left font-mono text-[10px] text-zinc-400">{name}</span>
      <div className="flex-1 h-3 rounded-full overflow-hidden bg-zinc-100">
        <div
          className="h-full rounded-full"
          style={{ width: `${pct}%`, backgroundColor: color }}
        />
      </div>
      <span className="font-mono text-[9px] text-zinc-500 w-10 text-right">{count}</span>
    </div>
  );
}

export function PetNames() {
  const show = 25;

  return (
    <div>
      <div className="mb-5 flex items-baseline justify-between">
        <span className="font-mono text-xs tracking-[0.16em] text-zinc-400">
          pet names
        </span>
      </div>
      <div className="grid gap-6 sm:grid-cols-2">
        <div>
          <div className="mb-3">
            <span className="font-mono text-[10px] text-zinc-400">sam calls her</span>
          </div>
          <div className="space-y-1.5">
            {sam.slice(0, show).map((p) => (
              <NameBar key={p.name} name={p.name} count={p.count} max={samMax} color="rgba(0,0,0,0.4)" />
            ))}
          </div>
        </div>
        <div>
          <div className="mb-3">
            <span className="font-mono text-[10px] text-zinc-400">dianchik calls him</span>
          </div>
          <div className="space-y-1.5">
            {dia.slice(0, show).map((p) => (
              <NameBar key={p.name} name={p.name} count={p.count} max={diaMax} color="rgba(180,140,20,0.7)" />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// src/lib/components/messages/PetNames.svelte
<script lang="ts">
	import petData from '../../../../data/messages/dianchik/petnames-data.json';

	interface PetName {
		name: string;
		count: number;
	}

	const sam = petData.sam as PetName[];
	const dia = petData.dianchik as PetName[];
	const samMax = sam[0]?.count ?? 1;
	const diaMax = dia[0]?.count ?? 1;

	const show = 25;
</script>

{#snippet nameBar(name: string, count: number, max: number, color: string)}
	<div class="flex items-center gap-1.5">
		<span class="w-24 shrink-0 truncate text-left font-mono text-[10px] text-zinc-600">{name}</span>
		<div class="h-3 flex-1 overflow-hidden rounded-full bg-zinc-100">
			<div
				class="h-full rounded-full"
				style="width: {(count / max) * 100}%; background-color: {color};"
			></div>
		</div>
		<span class="w-10 text-right font-mono text-[9px] text-zinc-600">{count}</span>
	</div>
{/snippet}

<div>
	<div class="mb-6 flex items-baseline justify-between">
		<span class="font-mono text-xs tracking-[0.16em] text-zinc-600">pet names</span>
	</div>
	<div class="grid gap-6 sm:grid-cols-2">
		<div>
			<div class="mb-3">
				<span class="font-mono text-[10px] text-zinc-600">dianchik calls him</span>
			</div>
			<div class="space-y-1.5">
				{#each dia.slice(0, show) as p (p.name)}
					{@render nameBar(p.name, p.count, diaMax, 'rgba(180,140,20,0.7)')}
				{/each}
			</div>
		</div>
		<div>
			<div class="mb-3">
				<span class="font-mono text-[10px] text-zinc-600">sam calls her</span>
			</div>
			<div class="space-y-1.5">
				{#each sam.slice(0, show) as p (p.name)}
					{@render nameBar(p.name, p.count, samMax, 'rgba(0,0,0,0.4)')}
				{/each}
			</div>
		</div>
	</div>
</div>
