// app/shelf/page.tsx
import type { Metadata } from "next";
import Image from "next/image";
import { ShelfHero } from "@/components/shelf/shelf-hero";
import { getBooks, type Book } from "@/lib/goodreads";

export const metadata: Metadata = {
  title: "shelf — threesam",
  description: "Books, media, and the things that shape how I think.",
};

// Books stuck in currently-reading for more than ~3 months are effectively abandoned;
// fall through to last-read rather than feature something stale.
const CURRENT_MAX_AGE_MS = 1000 * 60 * 60 * 24 * 90;

function pickCurrentlyReading(books: Book[]): Book | null {
  const cutoff = Date.now() - CURRENT_MAX_AGE_MS;
  return (
    books
      .filter((b) => b.addedAt.getTime() > cutoff)
      .sort((a, b) => b.addedAt.getTime() - a.addedAt.getTime())[0] ?? null
  );
}

function BookCover({ book }: { book: Book }) {
  return (
    <a
      href={`https://www.goodreads.com/book/show/${book.id}`}
      target="_blank"
      rel="noopener noreferrer"
      className="group relative block break-inside-avoid p-1.5 md:transition-[background-color,box-shadow] md:duration-300 md:ease-out md:hover:z-10 md:hover:bg-[var(--coin)] md:hover:shadow-[0_0_0_4px_var(--coin)]"
    >
      {book.coverUrl ? (
        <Image
          src={book.coverUrl}
          alt={book.cleanTitle}
          width={200}
          height={300}
          loading="lazy"
          sizes="(min-width: 1280px) 8vw, (min-width: 1024px) 10vw, (min-width: 768px) 12vw, (min-width: 640px) 16vw, 25vw"
          className="block h-auto w-full md:transition-[filter] md:duration-300 md:group-hover:grayscale"
        />
      ) : (
        <div className="flex aspect-2/3 w-full items-center justify-center bg-zinc-900 p-3 text-center text-xs text-zinc-600">
          {book.cleanTitle}
        </div>
      )}
    </a>
  );
}

export default async function ShelfPage() {
  const [currentlyReading, read] = await Promise.all([
    getBooks("currently-reading"),
    getBooks("read"),
  ]);

  const sorted = [...read].sort((a, b) => b.addedAt.getTime() - a.addedAt.getTime());

  const currentBook = pickCurrentlyReading(currentlyReading);

  const lastRead =
    [...read]
      .filter((b) => b.readAt)
      .sort((a, b) => b.readAt!.getTime() - a.readAt!.getTime())[0] ?? sorted[0] ?? null;

  const featured = currentBook ?? lastRead;
  const featuredLabel = currentBook ? "currently reading" : "last read";

  return (
    <main
      className="copy-lower min-h-screen pb-18"
      style={{ background: "linear-gradient(to bottom, var(--black) 40%, var(--white))", color: "var(--white)" } as React.CSSProperties}
    >
      <ShelfHero featured={featured} featuredLabel={featuredLabel} />

      <section className="columns-4 gap-0 overflow-hidden py-1.5 sm:columns-6 md:columns-8 lg:columns-10 xl:columns-12">
        {sorted.map((book) => (
          <BookCover key={book.id} book={book} />
        ))}
      </section>
    </main>
  );
}

// src/routes/shelf/+page.svelte
<script lang="ts">
  import SeoHead from "$lib/components/SeoHead.svelte";
  import ShelfHero from "$lib/components/ShelfHero.svelte";
  import { proxyImg } from "$lib/img";
  import type { PageData } from "./$types";

  let { data }: { data: PageData } = $props();
  let { sorted, featured, featuredLabel } = $derived(data);
</script>

<SeoHead
  title="shelf"
  description="Books, media, and the things that shape how I think."
  canonical="/shelf"
/>

<main
  class="copy-lower min-h-screen pb-18"
  style="background: linear-gradient(to bottom, var(--black) 40%, var(--white)); color: var(--white);"
>
  <ShelfHero {featured} {featuredLabel} />

  <section class="columns-4 gap-0 overflow-hidden py-1.5 sm:columns-6 md:columns-8 lg:columns-10 xl:columns-12">
    {#each sorted as book (book.id)}
      <a
        href={`https://www.goodreads.com/book/show/${book.id}`}
        target="_blank"
        rel="noopener noreferrer"
        class="group relative block break-inside-avoid p-1.5 md:transition-[background-color,box-shadow] md:duration-300 md:ease-out md:hover:z-10 md:hover:bg-[var(--coin)] md:hover:shadow-[0_0_0_4px_var(--coin)]"
      >
        {#if book.coverUrl}
          <img
            src={proxyImg(book.coverUrl, 200)}
            alt={book.cleanTitle}
            width="200"
            height="300"
            loading="lazy"
            class="block h-auto w-full md:transition-[filter] md:duration-300 md:group-hover:grayscale"
          />
        {:else}
          <div class="flex aspect-2/3 w-full items-center justify-center bg-zinc-900 p-3 text-center text-xs text-zinc-600">
            {book.cleanTitle}
          </div>
        {/if}
      </a>
    {/each}
  </section>
</main>
