// components/frame/anchor.tsx
"use client";

import { usePathname } from "next/navigation";
import { CloudCanvas } from "@/components/canvas/cloud-canvas";
import { LazyMount } from "@/components/lazy-mount";

// Pages where the ambient cloud footer would compete with the page's own
// full-bleed animations / immersive scroll experience. Also hidden on `/`
// because the homepage lays out its own 25dvh bottom cloud inside a
// single-viewport flex column. /thoughts and /sounds are full-viewport
// WIP pages whose own sketch background fills the screen — an extra
// cloud strip below pushes them past 100dvh and breaks the clean layout.
const HIDE_ON = ["/anything-but-analog"];
const EXACT_HIDE_ON = new Set(["/", "/thoughts", "/sounds", "/benny", "/dad"]);

export function Anchor() {
  const pathname = usePathname();
  if (EXACT_HIDE_ON.has(pathname)) return null;
  if (HIDE_ON.some((p) => pathname === p || pathname.startsWith(`${p}/`))) {
    return null;
  }
  return (
    <LazyMount className="relative h-[30dvh] w-full md:h-[50dvh]" rootMargin="200px">
      <CloudCanvas />
    </LazyMount>
  );
}

// src/lib/components/frame/Anchor.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import LazyMount from '$lib/components/LazyMount.svelte';
  import CloudCanvas from '$lib/components/canvas/CloudCanvas.svelte';

  // Pages where the ambient cloud footer competes with the page's own
  // full-bleed animations / immersive scroll. /thoughts and /sounds are
  // full-viewport WIP pages whose own sketch background fills the screen.
  const HIDE_PREFIXES = ['/anything-but-analog'];
  const EXACT_HIDE = new Set(['/', '/thoughts', '/sounds', '/benny', '/dad']);

  const pathname = $derived($page.url.pathname);

  const hidden = $derived(
    EXACT_HIDE.has(pathname) ||
      HIDE_PREFIXES.some((p) => pathname === p || pathname.startsWith(`${p}/`)),
  );
</script>

{#if !hidden}
  <!-- 200px scroll-ahead so the WebGL context warms before the user reaches it -->
  <LazyMount class="relative h-[30dvh] w-full md:h-[50dvh]" rootMargin="200px">
    <CloudCanvas />
  </LazyMount>
{/if}
