// app/anything-but-analog/page.tsx
import type { Metadata } from "next";
import { ArtGallery } from "@/components/art/art-gallery";
import { ArtScrollSync } from "@/components/art/art-scroll-sync";
import { ParticleTextCanvas } from "@/components/canvas/particle-text-canvas";
import { visibleSketches } from "@/lib/art/registry";
import { ogAndTwitter } from "@/lib/seo";

export const metadata: Metadata = {
  title: "anything but analog",
  description: "generative sketches.",
  ...ogAndTwitter("/og/anything-but-analog.png"),
};

export default function AnythingButAnalogPage() {
  const meta = visibleSketches.map((s) => ({
    slug: s.slug,
    date: s.date,
    description: s.description,
  }));
  return (
    <main
      id="art-scroller"
      className="h-dvh snap-y snap-mandatory overflow-y-scroll"
      style={{ backgroundColor: "var(--black)" }}
    >
      <ArtScrollSync />
      <section
        id="hero"
        data-art-slug="hero"
        className="relative h-dvh w-full snap-start overflow-hidden"
      >
        <ParticleTextCanvas />
      </section>
      <ArtGallery sketches={meta} />
    </main>
  );
}

// src/routes/anything-but-analog/+page.svelte
<script lang="ts">
  import SeoHead from '$lib/components/SeoHead.svelte';
  import ParticleTextCanvas from '$lib/components/canvas/ParticleTextCanvas.svelte';
  import ArtScrollSync from '$lib/components/art/ArtScrollSync.svelte';
  import ArtGallery from '$lib/components/art/ArtGallery.svelte';
  import { visibleSketches } from '$lib/art/registry';

  const meta = visibleSketches.map((s) => ({
    slug: s.slug,
    date: s.date,
    description: s.description,
  }));
</script>

<SeoHead
  title="anything but analog"
  description="generative sketches."
  ogImage="/og/anything-but-analog.png"
  canonical="/anything-but-analog"
/>

<main
  id="art-scroller"
  class="h-dvh snap-y snap-mandatory overflow-y-scroll"
  style="background-color: var(--black);"
>
  <ArtScrollSync />
  <section
    id="hero"
    data-art-slug="hero"
    class="relative h-dvh w-full snap-start overflow-hidden"
  >
    <ParticleTextCanvas />
  </section>
  <ArtGallery sketches={meta} />
</main>
