// components/lazy-mount.tsx
"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";

interface Props {
  children: ReactNode;
  /**
   * Minimum height reserved while the child isn't yet mounted. Prefer not
   * setting this when the parent already reserves space (e.g. a
   * `min-h-[100dvh]` section). Default: no reserved height.
   */
  placeholderMinHeight?: string;
  /** How early to mount before visible. Config — not a dep. */
  rootMargin?: string;
  /** Optional class on the wrapping div. */
  className?: string;
}

/**
 * Defers mounting of its children until the wrapper scrolls near the
 * viewport. Disconnects the IntersectionObserver after first mount so the
 * children stay mounted thereafter (unlike a virtualizer). Useful when a
 * page stacks many content blocks that each do heavy work on mount and
 * you want time-to-interactive to stay cheap.
 */
export function LazyMount({
  children,
  placeholderMinHeight,
  rootMargin = "400px",
  className = "",
}: Props) {
  const ref = useRef<HTMLDivElement>(null);
  const [mounted, setMounted] = useState(false);
  // Snapshot config into a ref so prop identity changes don't re-init the IO.
  const rootMarginRef = useRef(rootMargin);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const io = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting) {
          setMounted(true);
          io.disconnect();
        }
      },
      { rootMargin: rootMarginRef.current }
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);

  return (
    <div
      ref={ref}
      className={className}
      style={mounted || !placeholderMinHeight ? undefined : { minHeight: placeholderMinHeight }}
    >
      {mounted ? children : null}
    </div>
  );
}

// src/lib/components/LazyMount.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  interface Props {
    /**
     * How early to mount before visible. Snapshot on mount — prop
     * changes after mount have no effect (mirrors React original's
     * rootMarginRef snapshot).
     */
    rootMargin?: string;
    /**
     * Min height reserved while the child isn't yet mounted. Leave
     * unset when the parent already reserves space (e.g. min-h-dvh
     * section). Cleared once mounted.
     */
    placeholderMinHeight?: string;
    /** Optional class on the wrapping div. */
    class?: string;
    children?: import('svelte').Snippet;
  }

  let {
    rootMargin = '400px',
    placeholderMinHeight,
    class: klass = '',
    children,
  }: Props = $props();

  let visible = $state(false);
  let host: HTMLDivElement | undefined = $state();

  onMount(() => {
    if (!host) return;
    if (typeof IntersectionObserver === 'undefined') {
      visible = true;
      return;
    }
    // Capture rootMargin in a closure-local variable so prop identity
    // changes after mount have no effect (mirrors React original's
    // rootMarginRef snapshot).
    const margin = rootMargin;
    const io = new IntersectionObserver(
      (entries) => {
        if (entries.some((e) => e.isIntersecting)) {
          visible = true;
          io.disconnect();
        }
      },
      { rootMargin: margin },
    );
    io.observe(host);
    return () => io.disconnect();
  });
</script>

<div
  bind:this={host}
  class={klass}
  style={visible || !placeholderMinHeight ? undefined : `min-height: ${placeholderMinHeight}`}
>
  {#if visible && children}{@render children()}{/if}
</div>
