// components/canvas/breakout.tsx
import type { ReactNode } from "react";

interface BreakoutProps {
  children: ReactNode;
}

/**
 * A single sentence that breaks out of the flow — bigger, alone, breathing.
 * Use sparingly. It earned it.
 */
export function Breakout({ children }: BreakoutProps) {
  return (
    <p className="my-18 text-2xl leading-snug text-foreground md:my-24 md:text-3xl md:leading-snug">
      {children}
    </p>
  );
}

// src/lib/components/canvas/Breakout.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    children?: Snippet;
  }

  let { children }: Props = $props();
</script>

<!--
  A single sentence that breaks out of the flow — bigger, alone, breathing.
  Use sparingly. It earned it.
-->
<p class="my-18 text-2xl leading-snug text-foreground md:my-24 md:text-3xl md:leading-snug">
  {@render children?.()}
</p>
