// components/canvas/canvas.tsx
import type { ReactNode } from "react";

interface CanvasProps {
  children: ReactNode;
}

/**
 * A singular piece of work. Wraps Mood → Thoughts → Vision in order.
 * Each page composes its own Canvas with unique slot components.
 */
export function Canvas({ children }: CanvasProps) {
  return <article className="min-h-screen">{children}</article>;
}

// src/lib/components/canvas/Canvas.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    children?: Snippet;
  }

  let { children }: Props = $props();
</script>

<!--
  A singular piece of work. Wraps Mood → Thoughts → Vision in order.
  Each page composes its own Canvas with unique slot components.
-->
<article class="min-h-screen">
  {@render children?.()}
</article>
