// components/canvas/vision.tsx
import { Video } from "@/components/video";

interface VisionProps {
  src: string;
  poster?: string;
}

/**
 * Something the author filmed. A place they went. A moment they kept.
 * It plays. That's all it needs to do.
 */
export function Vision({ src, poster }: VisionProps) {
  return (
    <section className="w-full">
      <Video
        className="h-auto w-full"
        src={src}
        poster={poster}
        controls={false}
        autoPlay
        muted
        loop
        playsInline
      />
    </section>
  );
}

// src/lib/components/canvas/Vision.svelte
<script lang="ts">
  import Video from '$lib/components/Video.svelte';

  interface Props {
    src: string;
    poster?: string;
  }

  let { src, poster }: Props = $props();
</script>

<!--
  Something the author filmed. A place they went. A moment they kept.
  It plays. That's all it needs to do.
-->
<section class="w-full">
  <Video
    class="h-auto w-full"
    {src}
    {poster}
    controls={false}
    autoplay
    muted
    loop
    playsinline
  />
</section>
